[package]
name = "C8Emu"
version = "0.1.0"
authors = ["ThunderingWest4 <ThunderingWest4@github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixel-canvas = "0.2.1"
